FROM almalinux:9
ENV course="Devops and Amazon" \
    trainer="shiva yadav" \
    duration="3months"
 ARG USERNAME=shivayadav
RUN echo "Hello user: ${USERNAME}
#RUN echo "Hello ${trainer}" > /var/tmp/devops.txt
CMD [ "sleep","100" ]



#ARG ${username:-some_user} ---ve can override Arg  by this