FROM almalinux:9
ENV course="Devops and Amazon" \
    trainer= "shiva yadav" \
    duration="3months"

RUN  echo "Hello user ${username}" > /var/tmp/devops.txt



#ARG ${username:-some_user} ---ve can override Arg  by this